alias: Sunset
description: ""
triggers:
  - trigger: sun
    event: sunset
conditions: []
actions:
  - parallel:
      - action: light.turn_on
        data:
          brightness_pct: 100
          color_temp_kelvin: 2700
          transition: 0
        target:
          entity_id:
            - light.tl_driveway_left
            - light.tl_driveway_right
      - action: light.turn_on
        data:
          brightness_pct: 100
          color_temp_kelvin: 4600
          transition: 0
        target:
          entity_id:
            - light.tl_porch_1
            - light.tl_porch_2
      - action: switch.turn_on
        target:
          entity_id:
            - switch.tl_garage_plugs_switch_1
            - switch.tl_garage_plugs_switch_2
            - switch.tl_outside_plugs_switch_1
            - switch.tl_outside_plugs_switch_2
        data: {}
mode: single
